# Generated by Django 4.2.2 on 2023-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
    ]
