# Generated by Django 4.2.2 on 2023-06-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
